import type { Config } from "tailwindcss";

export default {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
      },
    },
  },
  plugins: [
    require('daisyui'),
  ],
  daisyui: {
    themes: [
      {
        cvfast: {
          primary: "#60a5fa",
          "primary-content": "#0a1120",
          secondary: "#60a5fa",
          "secondary-content": "#0a1120",
          accent: "#22d3ee",
          "accent-content": "#0a1120",
          neutral: "#18181b",
          "neutral-content": "#ffffff",
          "base-100": "#050505",
          "base-200": "#0d0d0f",
          "base-300": "#18181b",
          "base-content": "#ffffff",
          info: "#60a5fa",
          "info-content": "#0a1120",
          success: "#22c55e",
          "success-content": "#0a1120",
          warning: "#eab308",
          "warning-content": "#0a1120",
          error: "#ef4444",
          "error-content": "#0a1120",
          "--rounded-box": "16px",
          "--rounded-btn": "8px",
          "--rounded-badge": "9999px",
          "--animation-btn": "0.15s",
          "--animation-input": "0.2s",
        },
      },
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",
    ],
  },
} satisfies Config;
